/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_estacionamiento;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author USUARIO
 */
public class Alta_Vehiculo extends javax.swing.JPanel {

    Conexion_MYSQL conexion;
    ResultSet res;
    JComboBox cmbm;
    public Alta_Vehiculo() {
        initComponents();
        
         Obtener_Marcas();
         Obtener_Colores();
                 try {
            DefaultTableModel modelo = new DefaultTableModel();
            tabla_alta_vehiculo.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            
            String sql = "select a.id_auto,a.matricula,a.modelo,m.descripcion,c.descripcion from Autos a,Marcas m,Colores c where id_auto=id_auto and m.id_marca=a.id_marca and c.id_color=a.id_color;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Id_Auto");
            modelo.addColumn("Matricula");
            modelo.addColumn("Modelo");
            modelo.addColumn("Marca");
            modelo.addColumn("Color");
            
            
            int[] anchos = {70, 70, 70,70};
            for (int i = 0; i < tabla_alta_vehiculo.getColumnCount(); i++) {
//                tabla_alta_vehiculo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
         
         
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        cmbmarca = new javax.swing.JComboBox<>();
        cmbcolor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alta_vehiculo = new javax.swing.JTable();
        txtidauto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Registrar  Nuevo Vehículo");

        jLabel2.setText("Matricula");

        jLabel3.setText("Modelo");

        jLabel4.setText("Marca ");

        jLabel5.setText("Color");

        txtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodeloActionPerformed(evt);
            }
        });

        cmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la Marca" }));
        cmbmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmarcaActionPerformed(evt);
            }
        });

        cmbcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Color" }));
        cmbcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcolorActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla_alta_vehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_Auto", "Matricula", "Modelo", "Marca", "Color"
            }
        ));
        jScrollPane1.setViewportView(tabla_alta_vehiculo);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Registro de Vehículos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(txtidauto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(220, 220, 220)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidauto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodeloActionPerformed

    private void cmbmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmarcaActionPerformed

    
    }//GEN-LAST:event_cmbmarcaActionPerformed

    private void cmbcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcolorActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbcolorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtmatricula.getText().equals("") || txtmodelo.getText().equals("") || cmbmarca.getSelectedIndex()==0 || cmbcolor.getSelectedIndex()==0)
           JOptionPane.showMessageDialog(null,"Llena todos los campos ","Error",JOptionPane.ERROR_MESSAGE);
        else
        {
           
            conexion=new Conexion_MYSQL();
            String id_marca="";
            String id_color="";
            int i=0;
            boolean band=false;
          
            if(band==false)
            {
                
                try
                {
                    res=conexion.consultar("SELECT id_marca FROM Marcas WHERE descripcion='"
                        +cmbmarca.getSelectedItem().toString()+"'");

                    while(res.next())
                    {
                        id_marca=res.getString("id_marca");
                    }
                }
                catch(Exception e)
                {
                    //System.out.println("Error: "+e.getMessage());
                }
                
                 try
                {
                    res=conexion.consultar("SELECT id_color FROM Colores WHERE descripcion='"
                        +cmbcolor.getSelectedItem().toString()+"'");

                    while(res.next())
                    {
                        id_color=res.getString("id_color");
                    }
                }
                catch(Exception e)
                {
                   // System.out.println("Error: "+e.getMessage());
                }
                /*
                String SQL="INSERT INTO Productos(nombre,descripcion,id_clasificacion) VALUES('"
                        +txtprod.getText()+"','"+txtdesc.getText()+"',"+id+")";
                */
                String SQL="call registra_Automovil(0,'"+txtmatricula.getText()+"','"+txtmodelo.getText()+"',"+id_marca+","+id_color+")";
                
                System.out.println("Se ha realizado correctamente la siguiente sentencia :\n"+SQL+"\n\n");

                txtmatricula.setText("");
                txtmodelo.setText("");
                cmbmarca.setSelectedIndex(0);
                cmbcolor.setSelectedIndex(0);

                conexion.Updates(SQL);
                
            }
        }
                try {
            DefaultTableModel modelo = new DefaultTableModel();
            tabla_alta_vehiculo.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            String sql = "select a.id_auto,a.matricula,a.modelo,m.descripcion,c.descripcion from Autos a,Marcas m,Colores c where id_auto=id_auto and m.id_marca=a.id_marca and c.id_color=a.id_color;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Id_Auto");
            modelo.addColumn("Matricula");
            modelo.addColumn("Modelo");
            modelo.addColumn("Marca");
            modelo.addColumn("Color");
            
            
            int[] anchos = {70, 70, 70,70};
            for (int i = 0; i < tabla_alta_vehiculo.getColumnCount(); i++) {
//                tabla_alta_vehiculo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        conexion=new Conexion_MYSQL();
        String SQL="call eliminar_Auto("+txtidauto.getText()+")";
        System.out.println("Se ha realizado correctamente la sentencia :\n"+SQL+"\n\n");
        conexion.Updates(SQL);
       
        
        txtidauto.setText("");
        
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            tabla_alta_vehiculo.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            
            String sql = "select a.id_auto,a.matricula,a.modelo,m.descripcion,c.descripcion from Autos a,Marcas m,Colores c where id_auto=id_auto and m.id_marca=a.id_marca and c.id_color=a.id_color;";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Id_Auto");
            modelo.addColumn("Matricula");
            modelo.addColumn("Modelo");
            modelo.addColumn("Marca");
            modelo.addColumn("Color");
            
            
            int[] anchos = {70, 70, 70,70};
            for (int i = 0; i < tabla_alta_vehiculo.getColumnCount(); i++) {
//                tabla_alta_vehiculo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    void Obtener_Marcas()
    {
        
        conexion=new Conexion_MYSQL();
        try
        {
            res=conexion.consultar("SELECT * FROM Marcas ORDER BY descripcion");
            
            while(res.next())
            {
                cmbmarca.addItem(res.getString("descripcion"));
            }
        }
        catch(Exception e)
        {
            System.out.println("Error"+e.getMessage());
        }
        conexion.salir();
    }

      void Obtener_Colores()
    {
        
        conexion=new Conexion_MYSQL();
        try
        {
            res=conexion.consultar("SELECT * FROM Colores ORDER BY descripcion");
            
            while(res.next())
            {
                cmbcolor.addItem(res.getString("descripcion"));
            }
        }
        catch(Exception e)
        {
            //System.out.println("Error"+e.getMessage());
        }
        conexion.salir();
    }
     
      
      
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcolor;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_alta_vehiculo;
    private javax.swing.JTextField txtidauto;
    private javax.swing.JTextField txtmatricula;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
